Add new util method to return carbon runtimes
wso2/carbon-utils pull request #11
Opened 2017-06-16 09:35 UTC by daneshk

Resolves #10

2017-07-12 07:06 UTC, Kishanthan requested changes

2017-07-12 07:06 UTC, Kishanthan commented on components/org.wso2.carbon.utils/src/main/java/org/wso2/carbon/utils/Utils.java
> +        runtimes.parallel()
parallel would not give much performance here as there will only be few runtimes (<5)

2017-07-12 07:06 UTC, Kishanthan commented on components/org.wso2.carbon.utils/src/main/java/org/wso2/carbon/utils/Utils.java
> +                .forEach(profile -> Optional.ofNullable(profile.getFileName())
I don't think we need to do the Optional.ofNullable here. removing those would still work as expected according to the current logic.

2017-07-21 07:59 UTC, Kishanthan commented on components/org.wso2.carbon.utils/src/main/java/org/wso2/carbon/utils/Utils.java
> +                .forEach(profile -> Optional.ofNullable(profile.getFileName())
@daneshk , could you look at the above review comments?

2017-07-27 09:38 UTC, cnapagoda approved these changes

2017-07-28 06:57 UTC, Kishanthan approved these changes

2017-07-31 04:58 UTC, merged