Add runtime utils
wso2/carbon-utils pull request #2
Opened 2017-03-31 11:10 UTC by thusithathilina

Add utility methods to get runtime related info

2017-03-31 11:26 UTC, Niranjan-K commented
@thusithathilina : we would need to create an issue for this in this repo and link it from the kernel issue.

2017-03-31 11:30 UTC, Niranjan-K requested changes

2017-03-31 11:30 UTC, Niranjan-K commented on components/org.wso2.carbon.utils/src/main/java/org/wso2/carbon/utils/Utils.java
> +    public static Path getRuntimeHome() {
Shouldn't this be getRuntimePath?

2017-03-31 11:30 UTC, Niranjan-K commented on components/org.wso2.carbon.utils/src/main/java/org/wso2/carbon/utils/Utils.java
> +    public static Path getRuntimeHome(String runtimeName) throws IOException {
Shouldn't this be path instead of Home?

2017-03-31 11:30 UTC, Niranjan-K commented on components/org.wso2.carbon.utils/src/main/java/org/wso2/carbon/utils/internal/DataHolder.java
> +public class DataHolder {
@Since is missing

2017-04-03 03:31 UTC, thusithathilina commented on components/org.wso2.carbon.utils/src/main/java/org/wso2/carbon/utils/Utils.java
> +    public static Path getRuntimeHome() {
I followed the same style as getCarbonHome. If require we can change that as suggested

2017-04-03 03:31 UTC, thusithathilina commented on components/org.wso2.carbon.utils/src/main/java/org/wso2/carbon/utils/Utils.java
> +    public static Path getRuntimeHome(String runtimeName) throws IOException {
I followed the same style as getCarbonHome. If require we can change that as suggested

2017-04-03 04:54 UTC, Niranjan-K commented on components/org.wso2.carbon.utils/src/main/java/org/wso2/carbon/utils/Utils.java
> +    public static Path getRuntimeHome() {
In the case of CarbonHome which is the Server Home patch, but in the case of Runtime, there is the runtime name and runtime patch.

2017-04-03 04:54 UTC, Niranjan-K commented on components/org.wso2.carbon.utils/src/main/java/org/wso2/carbon/utils/Utils.java
> +    public static Path getRuntimeHome(String runtimeName) throws IOException {
In the case of CarbonHome which is the Server Home patch, but in the case of Runtime, there is the runtime name and runtime patch.

2017-04-03 06:54 UTC, Kishanthan approved these changes

2017-04-03 08:52 UTC, merged