Add carbon-utils feature
wso2/carbon-utils pull request #4
Opened 2017-04-05 12:31 UTC by thusithathilina

2017-04-05 13:04 UTC, thusithathilina commented
Resolves https://github.com/wso2/carbon-utils/issues/5

2017-04-06 04:32 UTC, Kishanthan requested changes

2017-04-06 04:32 UTC, Kishanthan commented on features/org.wso2.carbon.utils.feature/pom.xml
> +</project>
EOF line is missing

2017-04-06 05:13 UTC, vidurananayakkara commented on features/org.wso2.carbon.utils.feature/pom.xml
> +    <dependencies>
Should we remove the blank lines here?

2017-04-06 05:13 UTC, vidurananayakkara commented on features/org.wso2.carbon.utils.feature/pom.xml
> +
Should we remove the blank lines here?

2017-04-06 05:13 UTC, vidurananayakkara commented on features/org.wso2.carbon.utils.feature/pom.xml
> +
Same as the above comment. Should we remove the blank lines here?

2017-04-06 07:10 UTC, Kishanthan approved these changes

2017-04-06 08:18 UTC, Kishanthan requested changes

2017-04-06 08:18 UTC, Kishanthan commented on features/org.wso2.carbon.utils.feature/pom.xml
> +    <name>WSO2 Carbon Utils - Carbon Utils Feature</name>
This name is not consistent with other maven modules in this. See below build summary.

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] WSO2 Carbon - Utils Parent ......................... SUCCESS [  4.901 s]
[INFO] WSO2 Carbon - Utils ................................ SUCCESS [ 11.640 s]
[INFO] WSO2 Carbon Utils - Carbon Utils Feature ........... SUCCESS [  2.032 s]
[INFO] ------------------------------------------------------------------------

2017-04-06 08:59 UTC, Kishanthan approved these changes

2017-04-06 08:59 UTC, merged